name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: false
          gleam-version: '0.20.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: gleam format --check src test
      - run: gleam test
